# https://scrutinizer-ci.com/docs/
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
          - command: ./vendor/bin/phpunit --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: clover
  environment:
    php:
      version: 7.3
  dependencies:
    override:
      - composer install --prefer-source --no-interaction
filter:
  paths:
    - src/
  excluded_paths:
    - src/Http/Middleware/TransformsRequest.php
checks:
  php: true
coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
        negation: true